server:
  port: 8082
spring:
  application:
    name: inventory-service
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:h2:mem:product
eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka